title: This is the title
author: Andrew
email: amgrin29@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Description

# social links
twitter_username: your-twitter-handle
github_username:  @amgrin29

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
